version: "3.8"
networks:
  default:
    driver: bridge
  internal:
    external: true

services:
  airflow-webserver:
    build: . # Diz ao Coolify para usar o Dockerfile acima
    container_name: airflow_webserver
    command: bash -c "airflow db migrate && airflow webserver"
    expose:
      - "8080"
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW_DATABASE_URL}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    networks:
      - default
      - internal

  airflow-scheduler:
    build: . # Usa a mesma imagem customizada
    container_name: airflow_scheduler
    command: scheduler
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW_DATABASE_URL}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    networks:
      - default
      - internal
